<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:schema="http://mycompany.com/hr/schemas"
                  xmlns:tns="http://mycompany.com/hr/definitions"
                  targetNamespace="http://mycompany.com/hr/definitions">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://mycompany.com/hr/schemas"                      
                schemaLocation="party.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="PartyRequest">                                                 
        <wsdl:part element="schema:PartyRequest" name="PartyRequest"/>               
    </wsdl:message>
    <wsdl:portType name="PartyResource">                                                 
        <wsdl:operation name="Party">
            <wsdl:input message="tns:PartyRequest" name="PartyRequest"/>             
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PartyResourceBinding" type="tns:PartyResource">                  
        <soap:binding style="document"                                                   
            transport="http://schemas.xmlsoap.org/soap/http"/>                           
        <wsdl:operation name="Party">
            <soap:operation soapAction="http://mycompany.com/RequestParty"/>           
            <wsdl:input name="PartyRequest">
                <soap:body use="xml"/>                                               
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="PartyResourceService">
        <wsdl:port binding="tns:PartyResourceBinding" name="PartyResourcePort">          
            <soap:address location="http://localhost:8080/partyService/"/>             
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>